<a href="https://colab.research.google.com/github/mjiii25/prac_class/blob/main/LGBM%20%EB%AA%A8%EB%8D%B8%EB%A7%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [100]:
import numpy as np
import pandas as pd
import math
import os
import matplotlib.pyplot as plt

from sklearn.metrics import mean_absolute_error
from lightgbm import LGBMRegressor
from sklearn.model_selection import KFold

In [105]:
train = pd.read_csv('/content/drive/MyDrive/energy/new_train.csv')
test = pd.read_csv('/content/drive/MyDrive/energy/new_test.csv')
submission = pd.read_csv('/content/drive/MyDrive/energy/sample_submission.csv')

In [106]:
train.head()

num            date_time    target  ...   CDH         TW  corona
0    1  2020-06-01 00:00:00  8179.056  ...  -8.4  18.973374       1
1    1  2020-06-01 01:00:00  8135.640  ... -16.7  18.960338       1
2    1  2020-06-01 02:00:00  8107.128  ... -25.2  18.658598       1
3    1  2020-06-01 03:00:00  8048.808  ... -34.1  18.218957       1
4    1  2020-06-01 04:00:00  8043.624  ... -43.1  18.081523       1

[5 rows x 26 columns]

In [107]:
train.shape

(122400, 26)

In [108]:
test.head()

num            date_time  temperature  ...       CDH         TW  corona
0    1  2020-08-25 00:00:00    27.800000  ...  1.800000  30.027122       2
1    1  2020-08-25 01:00:00    27.633333  ...  3.433333  29.859547       2
2    1  2020-08-25 02:00:00    27.466667  ...  4.900000  29.694705       2
3    1  2020-08-25 03:00:00    27.300000  ...  6.200000  29.533017       2
4    1  2020-08-25 04:00:00    26.900000  ...  7.100000  29.116617       2

[5 rows x 25 columns]

In [109]:
test.shape

(10080, 25)

## 군집화 결과 (수연님)

In [138]:
# 1번 군집 
list1 = [1, 31, 30, 60, 3, 5, 24,32, 33, 15]
cl1 = train.drop(['date_time', 'date'], axis = 1)
cl1 = cl1[cl1['num'].isin(list1)==True]
#cl1 = train[train['num'].isin(list1)==True]
print(train.shape, cl1.shape)
print('1번 군집은 전체 데이터의 {0:.2f}'.format(cl1.shape[0]/train.shape[0] *100 )+' %를 차지함')

(122400, 26) (20400, 24)
1번 군집은 전체 데이터의 16.67 %를 차지함


In [139]:
# 2번 군집 
list1 = [2, 6, 7, 8, 13, 14, 16, 17, 18, 22, 23, 25, 26, 27, 37, 46, 47, 48, 52, 53, 54, 55, 56, 57 ,35, 38, 43, 44, 39, 45]
cl2 = train.drop(['date_time', 'date'], axis = 1)
cl2 = cl2[cl2['num'].isin(list1)==True]
#cl2 = train[train['num'].isin(list1)==True]
print(train.shape, cl2.shape)
print('2번 군집은 전체 데이터의 {0:.2f}'.format(cl2.shape[0]/train.shape[0] *100 )+' %를 차지함')

(122400, 26) (61200, 24)
2번 군집은 전체 데이터의 50.00 %를 차지함


In [141]:
# 3번 군집
l2 = [19,20,21,29,36,40,41,49,50,58,59]
cl3 = train.drop(['date_time', 'date'], axis = 1)
cl3 = cl3[cl3['num'].isin(l2)==True]
#cl3 = train[train['num'].isin(l2)==True]
print(train.shape, cl3.shape)
print('3번 군집은 전체 데이터의 {0:.2f}'.format(cl3.shape[0]/train.shape[0] *100 )+' %를 차지함')

(122400, 26) (22440, 24)
3번 군집은 전체 데이터의 18.33 %를 차지함


In [142]:
# 4번 군집
l3 = [14,9,10,11,12,30,42]
cl4 = train.drop(['date_time', 'date'], axis = 1)
cl4 = cl4[cl4['num'].isin(l3)==True]
#cl4 = train[train['num'].isin(l3)==True]
print(train.shape, cl4.shape)
print('4번 군집은 전체 데이터의 {0:.2f}'.format(cl4.shape[0]/train.shape[0] *100 )+' %를 차지함')

(122400, 26) (14280, 24)
4번 군집은 전체 데이터의 11.67 %를 차지함


In [143]:
# 5번 군집
l4 = [5,21,28,32,51, 34]
cl5 = train.drop(['date_time', 'date'], axis = 1)
cl5 = cl5[cl5['num'].isin(l4)==True]
#cl5 = train[train['num'].isin(l4)==True]
print(train.shape, cl5.shape)
print('5번 군집은 전체 데이터의 {0:.2f}'.format(cl5.shape[0]/train.shape[0] *100 )+' %를 차지함')

(122400, 26) (12240, 24)
5번 군집은 전체 데이터의 10.00 %를 차지함


In [144]:
# 군집 5개 완성!
cl1.reset_index(inplace=True, drop=True)
cl2.reset_index(inplace=True, drop=True)
cl3.reset_index(inplace=True, drop=True)
cl4.reset_index(inplace=True, drop=True)
cl5.reset_index(inplace=True, drop=True)

In [145]:
# 기술통계량 확인
train.describe()

num         target  ...             TW         corona
count  122400.000000  122400.000000  ...  122400.000000  122400.000000
mean       30.500000    2324.830866  ...      26.362236       1.105882
std        17.318173    2058.999326  ...       3.542213       0.307688
min         1.000000       0.000000  ...      13.436363       1.000000
25%        15.750000    1055.268000  ...      23.833377       1.000000
50%        30.500000    1700.352000  ...      26.278986       1.000000
75%        45.250000    2780.487000  ...      28.675256       1.000000
max        60.000000   17739.225000  ...      38.971260       2.000000

[8 rows x 24 columns]

In [119]:
cl1.describe()

num        target  ...            TW        corona
count  20400.00000  20400.000000  ...  20400.000000  20400.000000
mean      23.40000   4000.199927  ...     26.205680      1.105882
std       17.13051   2057.588422  ...      3.495996      0.307695
min        1.00000    884.304000  ...     15.177703      1.000000
25%        5.00000   2504.682000  ...     23.637000      1.000000
50%       27.00000   3204.576000  ...     26.192815      1.000000
75%       32.00000   5593.320000  ...     28.597333      1.000000
max       60.00000   9802.080000  ...     38.157722      2.000000

[8 rows x 24 columns]

In [120]:
cl2.describe()

num        target  ...            TW        corona
count  61200.000000  61200.000000  ...  61200.000000  61200.000000
mean      32.433333   2314.197573  ...     26.541799      1.105882
std       17.038690   2223.567823  ...      3.523607      0.307689
min        2.000000      0.000000  ...     13.975392      1.000000
25%       17.000000   1098.684000  ...     24.071890      1.000000
50%       36.000000   1656.288000  ...     26.454967      1.000000
75%       47.000000   2561.328000  ...     28.823881      1.000000
max       57.000000  17739.225000  ...     38.872384      2.000000

[8 rows x 24 columns]

In [121]:
cl3.describe()

num        target  ...            TW        corona
count  22440.000000  22440.000000  ...  22440.000000  22440.000000
mean      38.363636   1270.805991  ...     26.302397      1.105882
std       14.066861    719.891681  ...      3.545642      0.307694
min       19.000000    275.238000  ...     13.436363      1.000000
25%       21.000000    856.170000  ...     23.779269      1.000000
50%       40.000000   1097.941500  ...     26.161911      1.000000
75%       50.000000   1477.251000  ...     28.641924      1.000000
max       59.000000   4905.684000  ...     38.157722      2.000000

[8 rows x 24 columns]

In [122]:
cl4.describe()

num        target  ...            TW        corona
count  14280.000000  14280.000000  ...  14280.000000  14280.000000
mean      18.285714   2568.672497  ...     25.827033      1.105882
std       11.744276   1955.357567  ...      3.602703      0.307698
min        9.000000    347.652000  ...     15.177703      1.000000
25%       10.000000   1183.437000  ...     23.200383      1.000000
50%       12.000000   2030.022000  ...     25.612251      1.000000
75%       30.000000   3574.044000  ...     28.197786      1.000000
max       42.000000   9802.080000  ...     38.872384      2.000000

[8 rows x 24 columns]

In [123]:
cl5.describe()

num        target  ...            TW        corona
count  12240.000000  12240.000000  ...  12240.000000  12240.000000
mean      28.500000   1941.539742  ...     26.208722      1.105882
std       13.890012    722.919915  ...      3.468719      0.307700
min        5.000000    525.204000  ...     15.727177      1.000000
25%       21.000000   1416.028500  ...     23.687612      1.000000
50%       30.000000   2032.695000  ...     26.142099      1.000000
75%       34.000000   2422.224000  ...     28.503867      1.000000
max       51.000000   3890.160000  ...     38.157722      2.000000

[8 rows x 24 columns]

## LGBM 모델링

[참고] https://www.kaggle.com/janged/xgb-lgb

In [146]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [147]:
def print_best_params(model, params, cl_x, cl_y):
    grid_model = GridSearchCV(
        model, 
        param_grid = params,
        cv=5,
        scoring='neg_mean_squared_error')

    grid_model.fit(cl_x, cl_y)
    rmse = np.sqrt(-1*grid_model.best_score_)
    print(
        '{0} 5 CV 시 최적 평균 RMSE 값 {1}, 최적 alpha:{2}'.format(model.__class__.__name__, np.round(rmse, 4), grid_model.best_params_))
    return grid_model.best_estimator_

In [131]:
SEED = 30

In [149]:
lgb_params = {
    'objective':['regression'],
    'num_leave' : [1],
    'learning_rate' : [0.05],
    'n_estimators':[1000],
    'max_bin' : [80],
    'gpu_id':[0] ,         
    'tree_method':['gpu_hist'],
    'refit':[True]
}

lgb_model = LGBMRegressor()

#### cluster1

In [148]:
cl1_x = cl1.drop('target', axis = 1)
cl1_y = cl1[['target']]

In [132]:
x_train, x_test, y_train, y_test = train_test_split(cl1_x, cl1_y, random_state=SEED)

In [150]:
lgb_estimator_cl1 = print_best_params(lgb_model, lgb_params, cl1_x, cl1_y)

LGBMRegressor 5 CV 시 최적 평균 RMSE 값 2472.0638, 최적 alpha:{'gpu_id': 0, 'learning_rate': 0.05, 'max_bin': 80, 'n_estimators': 1000, 'num_leave': 1, 'objective': 'regression', 'refit': True, 'tree_method': 'gpu_hist'}


#### cluster 2

In [151]:
cl2_x = cl2.drop('target', axis = 1)
cl2_y = cl2[['target']]

In [152]:
x_train, x_test, y_train, y_test = train_test_split(cl2_x, cl2_y, random_state=SEED)

In [172]:
lgb_estimator_cl2 = print_best_params(lgb_model, lgb_params, cl2_x, cl2_y)

LGBMRegressor 5 CV 시 최적 평균 RMSE 값 2278.689, 최적 alpha:{'gpu_id': 0, 'learning_rate': 0.05, 'max_bin': 80, 'n_estimators': 1000, 'num_leave': 1, 'objective': 'regression', 'refit': True, 'tree_method': 'gpu_hist'}


#### cluster 3

In [154]:
cl3_x = cl3.drop('target', axis = 1)
cl3_y = cl3[['target']]

In [155]:
x_train, x_test, y_train, y_test = train_test_split(cl3_x, cl3_y, random_state=SEED)

In [156]:
lgb_estimator_cl3 = print_best_params(lgb_model, lgb_params, cl3_x, cl3_y)

LGBMRegressor 5 CV 시 최적 평균 RMSE 값 646.9296, 최적 alpha:{'gpu_id': 0, 'learning_rate': 0.05, 'max_bin': 80, 'n_estimators': 1000, 'num_leave': 1, 'objective': 'regression', 'refit': True, 'tree_method': 'gpu_hist'}


#### cluster 4

In [157]:
cl4_x = cl4.drop('target', axis = 1)
cl4_y = cl4[['target']]

In [158]:
x_train, x_test, y_train, y_test = train_test_split(cl4_x, cl4_y, random_state=SEED)

In [159]:
lgb_estimator_cl4 = print_best_params(lgb_model, lgb_params, cl4_x, cl4_y)

LGBMRegressor 5 CV 시 최적 평균 RMSE 값 1278.4376, 최적 alpha:{'gpu_id': 0, 'learning_rate': 0.05, 'max_bin': 80, 'n_estimators': 1000, 'num_leave': 1, 'objective': 'regression', 'refit': True, 'tree_method': 'gpu_hist'}


#### cluster 5

In [160]:
cl5_x = cl5.drop('target', axis = 1)
cl5_y = cl5[['target']]

In [161]:
x_train, x_test, y_train, y_test = train_test_split(cl5_x, cl5_y, random_state=SEED)

In [162]:
lgb_estimator_cl5 = print_best_params(lgb_model, lgb_params, cl5_x, cl5_y)

LGBMRegressor 5 CV 시 최적 평균 RMSE 값 539.688, 최적 alpha:{'gpu_id': 0, 'learning_rate': 0.05, 'max_bin': 80, 'n_estimators': 1000, 'num_leave': 1, 'objective': 'regression', 'refit': True, 'tree_method': 'gpu_hist'}


## predict

In [164]:
testt = test.drop(['date_time', 'date'], axis = 1)

In [166]:
testt.head()

num  temperature  windspeed   humidity  ...   SL       CDH         TW  corona
0    1    27.800000   1.500000  74.000000  ...  0.0  1.800000  30.027122       2
1    1    27.633333   1.366667  75.333333  ...  0.0  3.433333  29.859547       2
2    1    27.466667   1.233333  76.666667  ...  0.0  4.900000  29.694705       2
3    1    27.300000   1.100000  78.000000  ...  0.0  6.200000  29.533017       2
4    1    26.900000   1.166667  79.666667  ...  0.0  7.100000  29.116617       2

[5 rows x 23 columns]

#### cluster 1

In [175]:
lgb_preds_cl1 = lgb_estimator_cl1.predict(testt)

In [176]:
preds_cl1 = 0.5*lgb_preds_cl1
preds_cl1

array([377.78603392, 351.67493721, 352.78248973, ..., 954.48645093,
       885.97281628, 842.08241467])

#### cluster 2

In [177]:
lgb_preds_cl2 = lgb_estimator_cl2.predict(testt)

In [178]:
preds_cl2 = 0.5*lgb_preds_cl2
preds_cl2

array([377.78603392, 351.67493721, 352.78248973, ..., 954.48645093,
       885.97281628, 842.08241467])

#### cluster3

In [179]:
lgb_preds_cl3 = lgb_estimator_cl3.predict(testt)

In [180]:
preds_cl3 = 0.5*lgb_preds_cl3
preds_cl3

array([454.34754254, 366.36549018, 351.81829585, ..., 510.62492227,
       513.61768141, 819.40236605])

#### cluster4

In [181]:
lgb_preds_cl4 = lgb_estimator_cl4.predict(testt)

In [182]:
preds_cl4 = 0.5*lgb_preds_cl4
preds_cl4

array([ 612.59154573,  592.12346895,  592.12072624, ...,  945.53929067,
        774.30641182, 1493.69873856])

#### cluster5

In [183]:
lgb_preds_cl5 = lgb_estimator_cl5.predict(testt)

In [184]:
preds_cl5 = 0.5*lgb_preds_cl5
preds_cl5

array([1467.30206054, 1403.8577935 , 1392.44273292, ...,  651.04921355,
        559.36160691,  437.14150742])

--------------------------------------------------------------------------------------------------------------



DACON 베이스라인

In [ ]:
cross = KFold(n_splits = 5, shuffle = True, random_state = 42)
folds = []
for train_idx, valid_idx in cross.split(cl1_x, cl1_y):
  folds.append((train_idx, valid_idx))

In [ ]:
models={}
for fold in range(5):
    print(f'===================={fold+1}=======================')
    train_idx, valid_idx=folds[fold]
    X_train=cl1_x.iloc[train_idx, :]
    y_train=cl1_y.iloc[train_idx, :]
    X_valid=cl1_x.iloc[valid_idx, :]
    y_valid=cl1_y.iloc[valid_idx, :]
    
    model=LGBMRegressor(n_estimators=100)
    model.fit(X_train, y_train, eval_set=[(X_train, y_train), (X_valid, y_valid)], 
             early_stopping_rounds=30, verbose=100)
    models[fold]=model
    
    print(f'================================================\n\n')

====================1=======================


ValueError: ignored